-- AlterTable
ALTER TABLE `Task` MODIFY `status` ENUM('NOT_STARTED', 'IN_PROGRESS', 'READY_FOR_TESTING', 'TESTING', 'REWORK_REQUIRED', 'COMPLETED', 'BLOCKED', 'CANCELLED') NOT NULL DEFAULT 'NOT_STARTED';

-- AlterTable
ALTER TABLE `TaskUpdate` MODIFY `status` ENUM('NOT_STARTED', 'IN_PROGRESS', 'READY_FOR_TESTING', 'TESTING', 'REWORK_REQUIRED', 'COMPLETED', 'BLOCKED', 'CANCELLED') NOT NULL;

-- AlterTable
ALTER TABLE `User` ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;
